# ------- Branding Related Config ------- #
- name: INSTALLATION_NAME
  value: 'I9PRO'
- name: LOGO_THUMBNAIL
  value: 'https://api.inovmi.com/api/arq-public/i9pro/logo-inovmi-nova-favicon.png'
- name: LOGO
  value: 'https://api.inovmi.com/api/arq-public/i9pro/logo-inovmi-nova-favicon.png'
- name: LOGO_DARK
  value: 'https://api.inovmi.com/api/arq-public/i9pro/logo-nova-inovmi-white-favicon.png'
- name: BRAND_URL
  value: 'https://www.inovmi.com.br'
- name: WIDGET_BRAND_URL
  value: 'https://www.inovmi.com.br'
- name: BRAND_NAME
  value: 'I9PRO'
- name: TERMS_URL
  value: 'https://www.inovmi.com.br'
- name: PRIVACY_URL
  value: 'https://www.inovmi.com.br'
- name: DISPLAY_MANIFEST
  value: true
# ------- End of Branding Related Config ------- #
